# =============================================================================
# Base configuration for semantic-release
#
# =============================================================================
ci: true

branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "✨ Features"
          - type: fix
            section: "🐛 Bug Fixes"
          - type: perf
            section: "⚡ Performance"
          - type: refactor
            section: "♻️ Refactoring"
          - type: docs
            section: "📚 Documentation"
          - type: chore
            section: "🔧 Chores"
            hidden: false
          - type: ci
            section: "👷 CI/CD"
            hidden: false

  - "@semantic-release/github"
